# Generated by Django 3.1.7 on 2021-03-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('plural', models.CharField(max_length=255)),
                ('docs', models.CharField(max_length=255)),
                ('is_person', models.BooleanField(default=False)),
            ],
        ),
    ]
