# Generated by Django 3.1.7 on 2021-03-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(help_text='Entity name', max_length=255, unique=True),
        ),
    ]
