# Generated by Django 3.1.7 on 2021-03-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20210302_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='documentation',
            field=models.TextField(blank=True, help_text='Documentation', null=True),
        ),
    ]
