# Generated by Django 3.1.7 on 2021-03-01 23:58

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='variable_name',
        ),
        migrations.AddField(
            model_name='variable',
            name='default_value',
            field=models.CharField(blank=True, help_text='Default value of the variable.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='definition_period',
            field=models.CharField(blank=True, choices=[('MONTH', 'MONTH'), ('YEAR', 'YEAR'), ('ETERNITY', 'ETERNITY')], help_text='Period the variable is defined for', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='description',
            field=models.CharField(blank=True, help_text='Human-readable description', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='Entity the variable is defined for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variables', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='variable',
            name='name',
            field=models.CharField(default='', help_text='Variable name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='possibleValues',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='reference',
            field=models.CharField(blank=True, help_text='Legislative reference describing the variable', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='value_type',
            field=models.CharField(blank=True, choices=[('Int', 'Int'), ('Float', 'Float'), ('Boolean', 'Boolean'), ('String', 'String'), ('Date', 'Date'), ('Enum', 'Enum')], help_text='The value type of the variable', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='metadata',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
