# Generated by Django 3.1.7 on 2021-03-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0002_auto_20210301_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='possibleValues',
            new_name='possible_values',
        ),
    ]
