# Generated by Django 3.1.7 on 2021-03-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0003_auto_20210302_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='dependencies',
            field=models.ManyToManyField(blank=True, help_text='What other variables is this variable dependent upon? Found using the formula as returned by the OpenFisca API.', related_name='_variable_dependencies_+', to='variables.Variable'),
        ),
    ]
