# Generated by Django 3.1.7 on 2021-03-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0005_auto_20210302_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulavariable',
            name='date',
        ),
    ]
