# Generated by Django 3.1.7 on 2021-03-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0007_auto_20210304_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='description',
            field=models.TextField(blank=True, help_text='Human-readable description', null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='reference',
            field=models.TextField(blank=True, help_text='Legislative reference describing the variable', null=True),
        ),
    ]
