# Generated by Django 3.1.7 on 2021-03-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0007_auto_20210304_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='children',
            field=models.ManyToManyField(blank=True, to='variables.Variable'),
        ),
        migrations.DeleteModel(
            name='FormulaVariable',
        ),
    ]
