# Generated by Django 3.1.7 on 2021-03-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0007_auto_20210304_0036'),
        ('variables', '0008_auto_20210304_0059'),
    ]

    operations = [
    ]
