# Generated by Django 3.1.7 on 2021-03-09 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0009_merge_20210308_2243'),
        ('variables', '0009_auto_20210305_0456'),
    ]

    operations = [
    ]
