# Generated by Django 3.1.7 on 2021-03-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0010_merge_20210309_0409'),
        ('variables', '0010_merge_20210309_2044'),
    ]

    operations = [
    ]
