# Generated by Django 3.1.7 on 2021-03-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0011_merge_20210310_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
