name: Deploy to DEV
on:
  workflow_dispatch:
  push:
    branches: [develop]
  repository_dispatch: # Triggered by a `push` event on a submodule
    types: [dev-openfisca-ruleset-updated] # repository_dispatch must have 'type' == "submodule-updated"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.SAFEGUARD_ESTIMATOR_INTEGRATIONS_AZURE_CREDS }}

      - name: Execute build django dev
        run: |
          az vm run-command invoke -g ${{ secrets.AZURE_RESOURCE_GROUP_DEV }} -n ${{ secrets.AZURE_VM_NAME_DEV }} \
          --command-id RunShellScript \
          --scripts '
            set -e
            git config --global --add safe.directory /home/openfiscaAdmin/openfisca_nsw_safeguard
            cd /home/djangoApiAdmin/openfisca-djangoapi
            git fetch --all
            git reset --hard origin/develop
            docker compose up --build -d
            docker compose exec app bash entrypoint.sh setup_db
            docker compose exec app bash entrypoint.sh fetch_data
            docker compose exec app bash entrypoint.sh manage collectstatic --noinput
          '
